# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = uwsm-app -- hyprpaper
exec-once = /home/deoxizn/appimg/openrgb/OpenRGB_1.0rc3_x86_64_6fbcf62.AppImage --profile "deoxizn" --startminimized
