# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, hyprctl dispatch workspace 2 && uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, hyprctl dispatch workspace 1 && omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, M, Music, exec, hyprctl dispatch workspace 3 && spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
bindd = SUPER CTRL, D, Vesktop, exec, hyprctl dispatch workspace 6 && vesktop
bindd = SUPER, W, Battlenet, exec, hyprctl dispatch workspace 4 && env LUTRIS_SKIP_INIT=1 lutris lutris:rungameid/263

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, P, Google Photos, exec, omarchy-launch-webapp "https://photos.google.com/"
bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, Z, Photopea, exec, omarchy-launch-webapp "https://photopea.com"

#kill apps
bindd = SUPER, Q, Close window, killactive,

#unbind keys
unbind = SUPER W
unbind = SUPER, SPACE, W

#game mode
bind = SUPER, F1, exec, ~/.config/hypr/gamemode.sh
