#unbind keys
unbind = SUPER, W
unbind = SUPER SHIFT, M
unbind = SUPER, P
unbind = SUPER, A

# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, hyprctl dispatch workspace 2 && uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, hyprctl dispatch workspace 1 && omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
#bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
bindd = SUPER CTRL, D, Vesktop, exec, hyprctl dispatch workspace 6 && vesktop
#bindd = SUPER ALT, T, FastFetch, exec, kitty fish -c "ff; exec fish"

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
# F13-F16 keys (using XF86 key names from wev)
bind = , XF86Tools, exec, kitty fish -c "ff; exec fish"
bind = , XF86Launch5, exec, omarchy-launch-webapp "https://gemini.google.com/app"
bind = , XF86Launch6, exec, omarchy-launch-webapp "https://photopea.com"
bind = , XF86Launch7, exec, omarchy-launch-webapp "https://learn.omacom.io/2/the-omarchy-manual"
bindd = SUPER SHIFT, M, Music, exec, hyprctl dispatch workspace 3 && /home/devi/appimg/YTMDesktop/YouTube-Music-3.11.0.AppImage

#kill apps
bindd = SUPER, Q, Close window, killactive,

#game mode
bind = SUPER, F1, exec, ~/.config/hypr/gamemode.sh

# Reload wallpaper/hyprpaper
bindd = SUPER ALT, W, Reload hyprpaper, exec, pkill -x hyprpaper && setsid uwsm-app -- hyprpaper -c ~/.config/hypr/hyprpaper.conf >/dev/null 2>&1 &

#Kill/Enable Idle
bind = SUPER SHIFT, I, exec, pgrep -x hypridle > /dev/null && (killall hypridle && notify-send "Idle Inhibitor: Disabled") || (hypridle & disown && notify-send "Idle Inhibitor: Enabled")
