preload=~/Pictures/wallpaper/wallhaven-kx996m.jpg
preload=~/Pictures/wallpaper/wallhaven-g8dm6e.jpg
preload=~/Pictures/wallpaper/symbols_t.png

wallpaper {
    monitor = DP-1
    path = ~/Pictures/wallpaper/wallhaven-kx996m.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/wallpaper/symbols_t.png
    fit_mode = cover
}

splash = false
