preload=~/Pictures/wallpaper/11.png
preload=~/Pictures/wallpaper/momo_ayase_centered_gruvbox.png

wallpaper {
    monitor = DP-1
    path = ~/Pictures/wallpaper/11.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/wallpaper/momo_ayase_centered_gruvbox.png
    fit_mode = cover
}

splash = false
