# Learn how to configure Hyprland: https://wiki.hypr.land/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu

#Workspaces per monitor with scrolling layout
workspace = 1, monitor:DP-1, layout:scrolling, layoutopt:direction:right
workspace = 2, monitor:DP-1, layout:scrolling, layoutopt:direction:right
workspace = 3, monitor:DP-1, layout:scrolling, layoutopt:direction:right
workspace = 4, monitor:DP-1, layout:scrolling, layoutopt:direction:right
workspace = 5, monitor:DP-1, layout:scrolling, layoutopt:direction:right
workspace = 6, monitor:HDMI-A-1, layout:scrolling, layoutopt:direction:down
workspace = 7, monitor:HDMI-A-1, layout:scrolling, layoutopt:direction:down
workspace = 8, monitor:HDMI-A-1, layout:scrolling, layoutopt:direction:down
workspace = 9, monitor:HDMI-A-1, layout:scrolling, layoutopt:direction:down
workspace = 10, monitor:HDMI-A-1, layout:scrolling, layoutopt:direction:down

#Launch Apps in Specific Workspaces
windowrule = match:class (zen|chromium|brave-browser), workspace 1


windowrule = match:class (org.gnome.Nautilus|nautilus), workspace 2
windowrule = match:class (discord|vesktop), workspace 6
windowrule = match:class (spotify|Spotify), workspace 3
windowrule = match:class (Battle.net|World of Warcraft|steam_app_default), workspace 4
windowrule = match:class (com.github.th_ch.youtube_music), workspace 3

# Cursor theme
env = XCURSOR_THEME,Future-dark-cursors
env = XCURSOR_SIZE,24
exec-once = gsettings set org.gnome.desktop.interface cursor-theme Future-dark-cursors
exec-once = gsettings set org.gnome.desktop.interface cursor-size 24
