# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    allow_tearing = true
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

#Window Transparency Overrides
windowrule = match:title ^(.*- YouTube.*)$, opacity 1
windowrule = match:title ^(World of Warcraft)$, opacity 1
general {

}
#Game Tweaks
windowrule = match:class World of Warcraft, immediate yes
