engines_as_actions = true

[[entries]]
default = "true"
name = "🦁"
prefix = "b"
url = "https://search.brave.com/search?q=%TERM%"

[[entries]]
name = " YT"
prefix = "yt"
url = "https://www.youtube.com/results?search_query=%TERM%"

[[entries]]
name = "󰣇 Wiki"
prefix = "archw"
url = "https://wiki.archlinux.org/index.php?search=%TERM%"

[[entries]]
name = "󰣇 Pkgs"
prefix = "ap"
url = "https://archlinux.org/packages/?q=%TERM%"

[[entries]]
name = "󰣇 UR"
prefix = "aur"
url = "https://aur.archlinux.org/packages?O=0&K=%TERM%"
