# GENERATED by hexciri-theme-set-templates — do not edit
set -g fish_color_normal c7ccd1
set -g fish_color_command 6f8aad
set -g fish_color_keyword aa5b82
set -g fish_color_quote 95c7ae
set -g fish_color_redirection 73899f
set -g fish_color_end aec795
set -g fish_color_error cf867c
set -g fish_color_param c7ccd1
set -g fish_color_comment 747c84
set -g fish_color_selection eeeeee --background=d8e1d4
set -g fish_color_search_match eeeeee --background=d8e1d4
set -g fish_color_operator 73899f
set -g fish_color_escape aa5b82
set -g fish_color_autosuggestion 747c84
set -g fish_color_cancel cf867c
set -g fish_pager_color_progress 747c84
set -g fish_pager_color_prefix 6f8aad --bold
set -g fish_pager_color_completion c7ccd1
set -g fish_pager_color_description 747c84
set -g fish_pager_color_selected_background --background=d8e1d4
